# Generated by Django 3.1.7 on 2021-03-23 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-яёЁґҐіІїЇєЄ]{2,20}$', 'Only alfa min 2 max 20')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-яёЁґҐіІїЇєЄ]{2,20}$', 'Only alfa min 2 max 20')]),
        ),
    ]
